services:
  dnsfilt-analytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnsfilt-analytics
    ports:
      - "${ANALYTICS_PORT:-8081}:8081"
    env_file:
      - ${ENV_FILE:-.env}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
