import os
import shutil
import logging
import subprocess
from app.config import settings

logger = logging.getLogger(__name__)

class NginxService:
    def __init__(self):
        self.nginx_stream_path = settings.NGINX_STREAM_CONFIG_PATH
        self.backend_host = settings.NGINX_BACKEND_HOST or "127.0.0.1"

    def _sanitize_and_deduplicate_ports(self, active_resolvers: list) -> list[int]:
        """
        Validates, filters, and deduplicates ports to prevent malformed or redundant upstream entries.
        """
        valid_ports = []
        seen = set()

        for r in active_resolvers:
            try:
                raw_port = r.get("port") if isinstance(r, dict) else getattr(r, "port", None)
                if raw_port is None:
                    continue
                port_num = int(raw_port)
                # Valid non-privileged/privileged network port range
                if 1024 <= port_num <= 65535 and port_num not in seen:
                    seen.add(port_num)
                    valid_ports.append(port_num)
                elif port_num in seen:
                    logger.debug(f"Filtered out duplicate resolver port: {port_num}")
                else:
                    logger.warning(f"Ignored out-of-range resolver port: {port_num}")
            except (ValueError, TypeError) as pe:
                logger.warning(f"Skipping malformed resolver record '{r}': {pe}")

        return valid_ports

    def generate_nginx_stream_config(self, active_resolvers: list) -> str:
        """
        Generates modular NGINX stream upstream configuration.
        Ensures valid syntax even if resolver list is empty or partially corrupted.
        """
        ports = self._sanitize_and_deduplicate_ports(active_resolvers)
        servers_cfg = ""

        if ports:
            for p in ports:
                servers_cfg += f"    server {self.backend_host}:{p};\n"
        else:
            # Safe placeholder so NGINX upstream block syntax remains 100% valid
            logger.warning("No active resolver ports available. Writing fallback dummy upstream.")
            servers_cfg = f"    server {self.backend_host}:2053;\n"

        return f"""# ==============================================================================
# AUTOMATICALLY GENERATED BY dnsfilt-orchestrator
# DO NOT EDIT MANUALLY - Updated on cluster scaling and rolling upgrades
# ==============================================================================

upstream dns_udp_cluster {{
{servers_cfg}}}

upstream dns_tcp_cluster {{
{servers_cfg}}}
"""

    def update_and_reload(self, active_resolvers: list) -> bool:
        """
        Atomically writes updated NGINX stream upstream configuration and triggers reload.
        Uses atomic file replacement (.tmp -> final) and creates backups to prevent partial reads.
        """
        target_path = self.nginx_stream_path
        tmp_path = f"{target_path}.tmp"
        bak_path = f"{target_path}.bak"

        try:
            content = self.generate_nginx_stream_config(active_resolvers)
            os.makedirs(os.path.dirname(target_path), exist_ok=True)

            # 1. Backup current config if it exists
            if os.path.exists(target_path):
                try:
                    shutil.copy2(target_path, bak_path)
                except Exception as be:
                    logger.debug(f"Could not create backup of '{target_path}': {be}")

            # 2. Atomic write: write to .tmp file first, flush to disk, then replace
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.write(content)
                f.flush()
                os.fsync(f.fileno())

            os.replace(tmp_path, target_path)
            
            ports_count = len(self._sanitize_and_deduplicate_ports(active_resolvers))
            logger.info(f"Updated NGINX stream config at {target_path} with {ports_count} active resolver upstreams.")

            # 3. Trigger reload on NGINX (Container or Host System)
            self._trigger_nginx_reload()
            return True

        except Exception as e:
            logger.error(f"Error updating NGINX stream config at {target_path}: {e}")
            # Restore from backup if temp write failed
            if os.path.exists(bak_path) and not os.path.exists(target_path):
                try:
                    shutil.copy2(bak_path, target_path)
                    logger.info(f"Restored previous NGINX config from backup {bak_path}")
                except Exception:
                    pass
            # Clean up dangling temp file
            if os.path.exists(tmp_path):
                try:
                    os.remove(tmp_path)
                except Exception:
                    pass
            return False

    def _trigger_nginx_reload(self):
        """Triggers reload signal on NGINX container via Docker API, or host systemctl/nginx."""
        reloaded = False

        # Attempt 1: Signal NGINX Docker container if running under Docker
        try:
            from app.services.docker_service import docker_service
            if docker_service.client:
                try:
                    container = docker_service.client.containers.get(settings.NGINX_CONTAINER_NAME)
                    if container and container.status == "running":
                        # Send SIGHUP for zero-downtime graceful config reload
                        container.kill(signal="SIGHUP")
                        logger.info(f"Sent graceful SIGHUP reload signal to NGINX container '{settings.NGINX_CONTAINER_NAME}'")
                        reloaded = True
                except Exception:
                    pass
        except Exception as ex:
            logger.debug(f"Container reload notice: {ex}")

        # Attempt 2: If running on host, try systemctl or nginx -s reload
        if not reloaded:
            try:
                res = subprocess.run(["nginx", "-s", "reload"], capture_output=True, text=True, timeout=5)
                if res.returncode == 0:
                    logger.info("Executed 'nginx -s reload' successfully.")
                    reloaded = True
            except Exception:
                pass

        if not reloaded:
            try:
                res = subprocess.run(["systemctl", "reload", "nginx"], capture_output=True, text=True, timeout=5)
                if res.returncode == 0:
                    logger.info("Executed 'systemctl reload nginx' successfully.")
                    reloaded = True
            except Exception:
                pass

        if not reloaded:
            logger.debug("NGINX reload signal will take effect on next NGINX worker cycle.")

nginx_service = NginxService()
