import os
import shutil
import logging
import subprocess
from app.config import settings

logger = logging.getLogger(__name__)

class NginxService:
    def __init__(self):
        self.nginx_stream_path = settings.NGINX_STREAM_CONFIG_PATH
        self.backend_host = settings.NGINX_BACKEND_HOST or "10.0.0.222"

    def _sanitize_and_deduplicate_ports(self, active_resolvers: list) -> list[int]:
        """
        Validates, filters, and deduplicates ports to prevent malformed or redundant upstream entries.
        """
        valid_ports = []
        seen = set()

        for r in active_resolvers:
            try:
                raw_port = r.get("port") if isinstance(r, dict) else getattr(r, "port", None)
                if raw_port is None:
                    continue
                port_num = int(raw_port)
                # Valid non-privileged/privileged network port range
                if 1024 <= port_num <= 65535 and port_num not in seen:
                    seen.add(port_num)
                    valid_ports.append(port_num)
                elif port_num in seen:
                    logger.debug(f"Filtered out duplicate resolver port: {port_num}")
                else:
                    logger.warning(f"Ignored out-of-range resolver port: {port_num}")
            except (ValueError, TypeError) as pe:
                logger.warning(f"Skipping malformed resolver record '{r}': {pe}")

        return valid_ports

    def generate_nginx_stream_config(self, active_resolvers: list) -> str:
        """
        Generates modular NGINX stream upstream configuration.

        Each resolver entry uses its own container IP address and port, producing entries like:
            server 10.88.16.163:2054;
            server 10.88.16.164:2055;
            server 10.88.16.165:2056;

        ip_address is the Podman-assigned container IP stored in ResolverInstance.
        Falls back to backend_host if ip_address is absent for a given entry.
        """
        servers_cfg = ""
        seen = set()

        for r in active_resolvers:
            try:
                raw_port = r.get("port") if isinstance(r, dict) else getattr(r, "port", None)
                if raw_port is None:
                    continue
                port_num = int(raw_port)
                if not (1024 <= port_num <= 65535):
                    logger.warning(f"Ignored out-of-range resolver port: {port_num}")
                    continue
                if port_num in seen:
                    logger.debug(f"Filtered out duplicate resolver port: {port_num}")
                    continue
                seen.add(port_num)
                servers_cfg += f"    server {self.backend_host}:{port_num};\n"
            except (ValueError, TypeError) as pe:
                logger.warning(f"Skipping malformed resolver record '{r}': {pe}")

        if not servers_cfg:
            # Safe placeholder so NGINX upstream block syntax remains 100% valid
            logger.warning("No active resolver entries available. Writing fallback dummy upstream.")
            servers_cfg = f"    server {self.backend_host}:2053;\n"

        return f"""# ==============================================================================
# AUTOMATICALLY GENERATED BY dnsfilt-orchestrator
# DO NOT EDIT MANUALLY - Updated on cluster scaling and rolling upgrades
# ==============================================================================

upstream dns_udp_cluster {{
{servers_cfg}}}

upstream dns_tcp_cluster {{
{servers_cfg}}}
"""

    def update_and_reload(self, active_resolvers: list) -> bool:
        """
        Safely writes updated NGINX stream upstream configuration and triggers reload.
        Preserves bind-mount inodes in Docker/Podman environments by avoiding os.replace() on mountpoints.
        """
        target_path = self.nginx_stream_path

        try:
            content = self.generate_nginx_stream_config(active_resolvers)

            # 1. Skip write & reload if config has not changed
            if os.path.exists(target_path):
                try:
                    with open(target_path, "r", encoding="utf-8") as f:
                        current_content = f.read()
                    if current_content == content:
                        logger.debug("NGINX stream config is already up-to-date. Skipping reload.")
                        return True
                except Exception:
                    pass

            os.makedirs(os.path.dirname(target_path), exist_ok=True)

            # 2. Write in-place (preserving file inode for Docker/Podman bind mounts)
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(content)
                f.flush()
                os.fsync(f.fileno())

            logger.info(f"Updated NGINX stream config at {target_path}")

            # 3. Trigger reload on NGINX (Container or Host System)
            self._trigger_nginx_reload()
            return True

        except Exception as e:
            logger.error(f"Error updating NGINX stream config at {target_path}: {e}")
            return False

    def _trigger_nginx_reload(self):
        """Triggers reload signal on NGINX container via Docker API, or host systemctl/nginx."""
        reloaded = False

        # Attempt 1: Signal NGINX Docker container if running under Docker
        try:
            from app.services.docker_service import docker_service
            if docker_service.client:
                try:
                    container = docker_service.client.containers.get(settings.NGINX_CONTAINER_NAME)
                    if container and container.status == "running":
                        # Send SIGHUP for zero-downtime graceful config reload
                        container.kill(signal="SIGHUP")
                        logger.info(f"Sent graceful SIGHUP reload signal to NGINX container '{settings.NGINX_CONTAINER_NAME}'")
                        reloaded = True
                except Exception:
                    pass
        except Exception as ex:
            logger.debug(f"Container reload notice: {ex}")

        # Attempt 2: If running on host, try systemctl or nginx -s reload
        if not reloaded:
            try:
                res = subprocess.run(["nginx", "-s", "reload"], capture_output=True, text=True, timeout=5)
                if res.returncode == 0:
                    logger.info("Executed 'nginx -s reload' successfully.")
                    reloaded = True
            except Exception:
                pass

        if not reloaded:
            try:
                res = subprocess.run(["systemctl", "reload", "nginx"], capture_output=True, text=True, timeout=5)
                if res.returncode == 0:
                    logger.info("Executed 'systemctl reload nginx' successfully.")
                    reloaded = True
            except Exception:
                pass

        if not reloaded:
            logger.debug("NGINX reload signal will take effect on next NGINX worker cycle.")

nginx_service = NginxService()
